=== Squall-Leonheart/Taller_LM/datos/esquemafac.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="servicios">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GestionCatastral"/>
        <xs:element ref="GestionTerrito"/>
        <xs:element ref="AvaluosDesenglobes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GestionCatastral">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="facturas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="facturas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="factura" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="valor" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GestionTerrito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="facturas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AvaluosDesenglobes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="facturas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Squall-Leonheart/Taller_LM/datos/facturacion.xml
<?xml version="1.0" encoding="utf-8"?>
<servicios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquemafac.xsd">
    <GestionCatastral>
        <facturas>
            <factura>
                <fecha>2024-01-01</fecha>
                <nombre>IGAC</nombre>
                <valor>10000000</valor>
            </factura>
            <factura>
                <fecha>2024-02-01</fecha>
                <nombre>ANT</nombre>
                <valor>15000000</valor>
            </factura>
            <factura>
                <fecha>2024-03-01</fecha>
                <nombre>UAECD</nombre>
                <valor>8000000</valor>
            </factura>
            <factura>
                <fecha>2024-04-01</fecha>
                <nombre>Catastro Antioquia</nombre>
                <valor>12000000</valor>
            </factura>
            <factura>
                <fecha>2024-05-01</fecha>
                <nombre>IGAC</nombre>
                <valor>20000000</valor>
            </factura>
            <factura>
                <fecha>2024-06-01</fecha>
                <nombre>IGAC</nombre>
                <valor>18000000</valor>
            </factura>
            <factura>
                <fecha>2024-07-01</fecha>
                <nombre>ANT</nombre>
                <valor>15000000</valor>
            </factura>
            <factura>
                <fecha>2024-08-01</fecha>
                <nombre>Catastro Cundinamarca</nombre>
                <valor>10000000</valor>
            </factura>
            <factura>
                <fecha>2024-09-01</fecha>
                <nombre>ANT</nombre>
                <valor>15000000</valor>
            </factura>
            <factura>
                <fecha>2024-10-01</fecha>
                <nombre>IGAC</nombre>
                <valor>12000000</valor>
            </factura>
        </facturas>
    </GestionCatastral>
    <GestionTerrito>
        <facturas>
            <factura>
                <fecha>2023-01-01</fecha>
                <nombre>Sohacha</nombre>
                <valor>10000000</valor>
            </factura>
            <factura>
                <fecha>2023-02-01</fecha>
                <nombre>Cundinamarca</nombre>
                <valor>15000000</valor>
            </factura>
            <factura>
                <fecha>2023-03-01</fecha>
                <nombre>Medellin</nombre>
                <valor>8000000</valor>
            </factura>
            <factura>
                <fecha>01-04-2023</fecha>
                <nombre>Pereira</nombre>
                <valor>12000000</valor>
            </factura>
            <factura>
                <fecha>01-05-2023</fecha>
                <nombre>Zipaquira</nombre>
                <valor>20000000</valor>
            </factura>
            <factura>
                <fecha>01-06-2023</fecha>
                <nombre>Barbosa</nombre>
                <valor>18000000</valor>
            </factura>
            <factura>
                <fecha>01-07-2023</fecha>
                <nombre>La Dorada</nombre>
                <valor>15000000</valor>
            </factura>
            <factura>
                <fecha>01-08-2023</fecha>
                <nombre>Puerto Salgar</nombre>
                <valor>10000000</valor>
            </factura>
            <factura>
                <fecha>01-09-2023</fecha>
                <nombre>Girardot</nombre>
                <valor>15000000</valor>
            </factura>
            <factura>
                <fecha>01-10-2023</fecha>
                <nombre>Cali</nombre>
                <valor>12000000</valor>
            </factura>
        </facturas>
    </GestionTerrito>
    <AvaluosDesenglobes>
        <facturas>
            <factura>
                <fecha>15-01-2025</fecha>
                <nombre>Carlos</nombre>
                <valor>5000000</valor>
            </factura>
            <factura>
                <fecha>01-02-2025</fecha>
                <nombre>Luis</nombre>
                <valor>8000000</valor>
            </factura>
            <factura>
                <fecha>01-03-2025</fecha>
                <nombre>Mar√≠a</nombre>
                <valor>8000000</valor>
            </factura>
            <factura>
                <fecha>10-03-2025</fecha>
                <nombre>Lina</nombre>
                <valor>12000000</valor>
            </factura>
            <factura>
                <fecha>11-04-2025</fecha>
                <nombre>Mery</nombre>
                <valor>9000000</valor>
            </factura>
            <factura>
                <fecha>01-05-2025</fecha>
                <nombre>Jairo</nombre>
                <valor>8000000</valor>
            </factura>
            <factura>
                <fecha>01-06-2025</fecha>
                <nombre>Diana</nombre>
                <valor>15000000</valor>
            </factura>
            <factura>
                <fecha>15-06-2025</fecha>
                <nombre>Marcela</nombre>
                <valor>4000000</valor>
            </factura>
            <factura>
                <fecha>14-07-2025</fecha>
                <nombre>Carlos</nombre>
                <valor>6000000</valor>
            </factura>
            <factura>
                <fecha>01-08-2025</fecha>
                <nombre>Fernanda</nombre>
                <valor>12000000</valor>
            </factura>
        </facturas>
    </AvaluosDesenglobes>
</servicios>
